# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BaFBVrSffZAozZMehiLuuC-BCiLPVP6-
"""

import streamlit as st
import pandas as pd
import joblib
import numpy as np

# Configuración y Estética
st.set_page_config(page_title="Industrial Health Monitor", layout="wide")
st.title("🏭 Sistema de Mantenimiento Predictivo 4.0")

# Cargar modelos
model = joblib.load('modelo_produccion.pkl')
scaler = joblib.load('scaler_industrial.pkl')
encoder = joblib.load('encoder_tipo.pkl')

# --- SIDEBAR: Entradas de Sensores ---
st.sidebar.header("📥 Telemetría en Tiempo Real")

tipo = st.sidebar.selectbox("Tipo de Producto", ['L', 'M', 'H'], help="L: Low (Tolerancias bajas), M: Medium, H: High")
air_t = st.sidebar.number_input("Temp. Ambiente [K]", value=300.0, step=0.1)
proc_t = st.sidebar.number_input("Temp. Proceso [K]", value=310.0, step=0.1)
rpm = st.sidebar.number_input("Velocidad [RPM]", value=1500, step=10)
torque = st.sidebar.number_input("Torque [Nm]", value=40.0, step=0.5)
wear = st.sidebar.number_input("Desgaste Herramienta [min]", value=0, step=1)

# --- Feature Engineering en Caliente ---
temp_diff = proc_t - air_t
mech_effort = torque * wear

# Preparar datos
input_df = pd.DataFrame([[tipo, air_t, proc_t, rpm, torque, wear, temp_diff, mech_effort]],
                        columns=['Type', 'Air_temperature', 'Process_temperature', 'Rotational_speed', 'Torque', 'Tool_wear', 'Temp_Diff', 'Mechanical_Effort'])

# Transformar
input_df['Type'] = encoder.transform(input_df[['Type']])
cols = ['Air_temperature', 'Process_temperature', 'Rotational_speed', 'Torque', 'Tool_wear', 'Temp_Diff', 'Mechanical_Effort']
input_df[cols] = scaler.transform(input_df[cols])

# --- PREDICCIÓN Y UI ---
st.divider()
col1, col2 = st.columns([1, 2])

with col1:
    if st.button('🚀 Diagnosticar Máquina', use_container_width=True):
        pred = model.predict(input_df)[0]
        probs = model.predict_proba(input_df)[0]

        labels = ['Normal', 'TWF (Desgaste)', 'HDF (Térmico)', 'PWF (Potencia)', 'OSF (Sobreesfuerzo)']

        if pred == 0:
            st.success(f"### ESTADO: {labels[0]}")
            st.balloons()
        else:
            st.error(f"### ALERTA: {labels[pred]}")

        # Gráfico de barras de probabilidad
        st.write("#### Probabilidades:")
        prob_data = pd.DataFrame({'Causa': labels, 'Confianza': probs})
        st.bar_chart(prob_data.set_index('Causa'))

with col2:
    st.info("### 🔍 Análisis de Ingeniería")
    st.write(f"**Gradiente Térmico:** {temp_diff:.2f} K")
    st.write(f"**Esfuerzo Mecánico:** {mech_effort:.2f} Nm·min")

    # Lógica de advertencia de ingeniero
    if temp_diff < 8.5:
        st.warning("⚠️ Gradiente térmico bajo. Riesgo de fallo por disipación (HDF).")
    if wear > 200:
        st.warning("⚠️ Desgaste crítico (>200 min). Riesgo inminente de rotura (TWF/OSF).")